#ifndef _CONSTANT_BUFFER_H
#define _CONSTANT_BUFFER_H

#include <d3d11.h>
#include <DirectXMath.h>

using namespace DirectX;

enum CONSTANT_BUFFER_LAYOUT {
	CONSTANT_BUFFER_LAYOUT_PER_FRAME,
	CONSTANT_BUFFER_LAYOUT_PER_MODEL
};

// CONSTANT BUFFERS MUST BE IN MULTIPLES OF 16 BYTES!
// CONSTANT BUFFERS MUST BE IN MULTIPLES OF 16 BYTES!
// Add padding where necessary.
// Did I mention?: CONSTANT BUFFERS MUST BE IN MULTIPLES OF 16 BYTES!

struct CONSTANT_BUFFER_PER_FRAME {
	XMFLOAT4X4 view;
	XMFLOAT4X4 proj;
	XMFLOAT4X4 viewProj;
};

struct CONSTANT_BUFFER_PER_MODEL {
	XMFLOAT4X4 world;
};

#endif // _CONSTANT_BUFFER_H