#include "Constants.h"

const WCHAR* vShaderNames[] = {
	L"ColoredVertex.cso",
	L"TexturedVertex.cso",
	L"TexturedInstancedVertex.cso",
	L"TexturedInstancedLightingVertex.cso",
	L"SkyboxVertex.cso",
	L"FontVertex.cso",
	L"2DVertex.cso"
};

const WCHAR* pShaderNames[] = {
	L"ColoredPixel.cso",
	L"TexturedPixel.cso",
	L"TexturedInstancedPixel.cso",
	L"TexturedInstancedLightingPixel.cso",
	L"SkyboxPixel.cso",
	L"FontPixel.cso",
	L"2DPixel.cso"
};

const TEXTURE_DESCRIPTION TEXTURE_DESCRIPTIONS[TM_NUM_TEXTURES] = {
	// NAME, TYPE, FILE FORMAT
	{ L"default.png" , TM_TYPE_DIFFUSE, TM_FILE_FORMAT_WIC },
	{ L"marble.png", TM_TYPE_DIFFUSE, TM_FILE_FORMAT_WIC },
	{ L"sand.jpg", TM_TYPE_DIFFUSE, TM_FILE_FORMAT_WIC },
	{ L"scales.png", TM_TYPE_DIFFUSE, TM_FILE_FORMAT_WIC },
	
	{ L"frigate/space_frigate_6_color.png", TM_TYPE_DIFFUSE, TM_FILE_FORMAT_WIC },
	{ L"frigate/space_frigate_6_bump.gif", TM_TYPE_NORMAL, TM_FILE_FORMAT_WIC },
	{ L"frigate/space_frigate_6_specular.png", TM_TYPE_SPECULAR, TM_FILE_FORMAT_WIC },
	{ L"frigate/space_frigate_6_illumination.png", TM_TYPE_ILLUMINATION, TM_FILE_FORMAT_WIC },

	{ L"spaceCubemap3.dds", TM_TYPE_CUBEMAP, TM_FILE_FORMAT_DDS_CUBEMAP },
	{ L"earth.dds", TM_TYPE_CUBEMAP, TM_FILE_FORMAT_DDS_CUBEMAP },

	{ L"ascii.png", TM_TYPE_DIFFUSE, TM_FILE_FORMAT_WIC },

	{ L"Texture Space Invader.png",TM_TYPE_DIFFUSE, TM_FILE_FORMAT_WIC},

	{ L"ResumeButton.png", TM_TYPE_DIFFUSE, TM_FILE_FORMAT_WIC},
	{ L"StartButtonUp.png", TM_TYPE_DIFFUSE, TM_FILE_FORMAT_WIC},
	{ L"QuitButton.png", TM_TYPE_DIFFUSE, TM_FILE_FORMAT_WIC},
};

const WCHAR* meshNames[] = { 
	L"Cube",
	L"sphere.fbx",
	L"frigate.fbx",
	L"Space Invader.fbx",
	L"Button"
};

const MATERIAL_DESCRIPTION MATERIAL_DESCRIPTIONS[NUM_MATERIALS] = {
	// PUT MATERIALS HERE
	{ 
		L"Default",
		MATERIAL_DEFAULT,
		VSHADER_TEXTURED_LIT_INSTANCED,
		PSHADER_TEXTURED_LIT_INSTANCED,
		TM_TEXTURE_DEFAULT,
		TM_FILTER_POINT,
		CONSTANT_BUFFER_LAYOUT_PER_MODEL 
	},
	{ 
		L"Marble",
		MATERIAL_MARBLE,
		VSHADER_TEXTURED_LIT_INSTANCED,
		PSHADER_TEXTURED_LIT_INSTANCED,
		TM_TEXTURE_MARBLE,
		TM_FILTER_ANISO_4X,
		CONSTANT_BUFFER_LAYOUT_PER_MODEL 
	},
	{ 
		L"Colored",
		MATERIAL_MARBLE,
		VSHADER_COLORED,
		PSHADER_COLORED,
		TM_TEXTURE_MARBLE,
		TM_FILTER_POINT,
		CONSTANT_BUFFER_LAYOUT_PER_MODEL 
	},
	{ 
		L"Frigate",
		MATERIAL_FRIGATE,
		VSHADER_TEXTURED_LIT_INSTANCED,
		PSHADER_TEXTURED_LIT_INSTANCED,
		TM_TEXTURE_FRIGATE_DIFFUSE,
		TM_FILTER_ANISO_4X,
		CONSTANT_BUFFER_LAYOUT_PER_MODEL 
	},
	{
		L"Skybox",
		MATERIAL_SKYBOX,
		VSHADER_SKYBOX,
		PSHADER_SKYBOX,
		TM_TEXTURE_SPACE_CUBEMAP,
		TM_FILTER_ANISO_4X,
		CONSTANT_BUFFER_LAYOUT_PER_MODEL 
	},
	{
		L"Text",
		MATERIAL_TEXT,
		VSHADER_TEXT,
		PSHADER_TEXT,
		TM_TEXTURE_TEXT,
		TM_FILTER_ANISO_4X,
		CONSTANT_BUFFER_LAYOUT_PER_MODEL 
	},
	{
		L"Space Invader",
		MATERIAL_INVADER,
		VSHADER_TEXTURED_LIT_INSTANCED,
		PSHADER_TEXTURED_LIT_INSTANCED,
		TM_TEXTURE_INVADER_DIFFUSE,
		TM_FILTER_ANISO_4X,
		CONSTANT_BUFFER_LAYOUT_PER_MODEL
	},
	{
		L"Start Button",
		MATERIAL_START_BUTTON,
		VSHADER_2D,
		PSHADER_2D,
		TM_TEXTURE_START_BUTTON_UP,
		TM_FILTER_ANISO_4X,
		CONSTANT_BUFFER_LAYOUT_PER_MODEL
	},
	{
		L"Return Button",
		MATERIAL_RETURN_BUTTON,
		VSHADER_2D,
		PSHADER_2D,
		TM_TEXTURE_RETURN_BUTTON,
		TM_FILTER_ANISO_4X,
		CONSTANT_BUFFER_LAYOUT_PER_MODEL
	},
	{
		L"Quit Button",
		MATERIAL_QUIT_BUTTON,
		VSHADER_2D,
		PSHADER_2D,
		TM_TEXTURE_QUIT_BUTTON,
		TM_FILTER_ANISO_4X,
		CONSTANT_BUFFER_LAYOUT_PER_MODEL
	}
};